---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
  labels:
    type: appserver
    author: Sai
spec:
  replicas: 3
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: mytomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9999





