---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    type: webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: httpd-rs
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090






